os: osx
language: generic
python: 3.7
env:
  global:
    - LULLAPY_ROOT=$TRAVIS_BUILD_DIR/lullapy
    - ASSEMBLY_NAME=Andeart.SystemConsole
    - ASSEMBLY_BIN_PATH=./SystemConsole/SystemConsole/bin
    - UNITY_NOPROXY="localhost,127.0.0.1"
    - UNITY_DOWNLOAD_CACHE="$TRAVIS_BUILD_DIR/unity_download_cache"
  matrix:
    - CONFIG_NAME=Debug
cache:
    directories:
      - unity_download_cache
before_install:
  - chmod a+x ./tools/*.sh
  - chmod -R a+rw ./unity_download_cache
  - chown -R travis:$travis /root/.cache/
  - chmod -R a+rw /root/.cache/
install:
  - pip3 install -e $LULLAPY_ROOT
  - ./tools/install-unity.sh
script:
  - ./tools/before_script.sh
  - ./tools/run-unity.sh