os: osx
language: generic
python: 3.7
env:
  global:
    - LULLAPY_ROOT=$TRAVIS_BUILD_DIR/lullapy
    - ASSEMBLY_NAME=Andeart.SystemConsole
    - ASSEMBLY_BIN_PATH=./SystemConsole/SystemConsole/bin
  matrix:
    - CONFIG_NAME=Debug
cache:
    directories:
     - /Applications
before_install:
  - chmod a+x ./tools/*.sh
install:
  - pip3 install -e $LULLAPY_ROOT
  - ./tools/install-unity.sh
script:
  - ./tools/run-unity.sh