os: osx
language: generic
python: 3.7
env:
  global:
    - LULLAPY_ROOT=$TRAVIS_BUILD_DIR/lullapy
    - ASSEMBLY_NAME=Andeart.SystemConsole
    - ASSEMBLY_BIN_PATH=./SystemConsole/SystemConsole/bin
  matrix:
    - CONFIG_NAME=Release
    - CONFIG_NAME=Debug
before_install:
  - chmod a+x ./tools/*.sh
install:
  - pip3 install -e $LULLAPY_ROOT
  - ./tools/install-unity.sh
script:
  - python3 -m andeart.lullapy.unitytest -u "/Applications/Unity/Unity.app/Contents/MacOS/Unity" -p "./SystemConsole.Demo" -m editmode -r "$(pwd)/testresults.xml"